"""empty message

Revision ID: 694462fe790c
Revises: 89bc7873a3e0
Create Date: 2022-07-22 07:58:20.677358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694462fe790c'
down_revision = '89bc7873a3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_acl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('acl_type', sa.Enum('SELECT', 'OPTIMIZE', 'TRUNCATE', 'CACHE', 'DDL_SCHEMAS', 'DDL_VIEWS', 'DDL_TABLES', 'DDL_FUNCTIONS', 'DML', 'DATA_LOAD', 'DATA_ADD', 'DESCRIBE', 'USE', 'SET', name='sqlacl'), nullable=False),
    sa.Column('acl_permission', sa.Enum('ALLOW', 'DENY', name='sqlaclpermission'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'data_source_id', 'acl_type', 'acl_permission', name='unique_acl_permission')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_acl')
    # ### end Alembic commands ###
